version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musamin-app
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - musamin

  webserver:
    image: nginx:alpine
    container_name: musamin-webserver
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    volumes_from:
      - app
    networks:
      - musamin

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musamin-reverb
    restart: unless-stopped
    working_dir: /var/www
    command: php /var/www/artisan reverb:start --host=0.0.0.0 --port=8081
    ports:
      - "8081:8081"
    networks:
      - musamin

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musamin-queue
    restart: unless-stopped
    working_dir: /var/www
    command: php /var/www/artisan queue:work redis --sleep=3 --tries=3
    networks:
      - musamin

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musamin-scheduler
    restart: unless-stopped
    working_dir: /var/www
    command: php /var/www/artisan schedule:work
    networks:
      - musamin

networks:
  musamin:
    driver: bridge